name: gem-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - myst_nb
  - notebook
  - sphinx
  - sphinx-rtd-theme
  - ipykernel
  - nbconvert
  - pandoc
  - pip
  - pip:
      - nbsphinx